### ISSUE TITLE
error in running test controller

### ISSUE THREAD

**Issue by rezamarandi** [hussaintamboli/Celery-CI#1]
hi , 
i installed a clean CI , now when i try to use it , i get this message :

A PHP Error was encountered

Severity: Notice

Message: Undefined property: CeleryController::$load

Filename: controllers/celerycontroller.php

Line Number: 6

**Comment by hussaintamboli** [comment]
I forgot to call the constructor of parent class in celerycontroller.

```
parent::__construct();
```

Modified the code. Thanks for reporting the issue.
