### ISSUE TITLE
error in running test controller

### ISSUE THREAD

**Issue by rezamarandi** [hussaintamboli/Celery-CI#2]
A PHP Error was encountered

Severity: Notice

Message: Undefined property: CeleryController::$ci

Filename: controllers/celerycontroller.php

Line Number: 18

you should change line number 18 to : 

$result = $this->celery->PostTask('tasks.add', array(2, 3));

**Comment by hussaintamboli** [comment]
Done. Thanks for pointing it out. 

I didn't test it after I resolved #1. Thanks again for bringing another issue.

**Comment by rezamarandi** [comment]
you're welcome
